/**
 * Token Hashing Utility — Auth Service
 *
 * SHA-256 hash for refresh tokens before storing in Postgres.
 *
 * Why SHA-256 instead of bcrypt?
 *   Refresh tokens are high-entropy random strings generated by jwt.sign(),
 *   not human-chosen passwords. Dictionary/rainbow-table attacks don't apply.
 *   SHA-256 is:
 *     1. Deterministic — we can look up a token by its hash in one query.
 *     2. Fast — no salt/rounds overhead, so token refresh doesn't add latency.
 *   bcrypt is designed to be slow (that's its feature for passwords), which
 *   would make every refresh-token lookup unnecessarily expensive.
 */

const crypto = require('crypto');

/**
 * Hash a raw token string using SHA-256.
 * @param {string} rawToken - The raw JWT refresh token
 * @returns {string} 64-char hex digest
 */
function hashToken(rawToken) {
    return crypto.createHash('sha256').update(rawToken).digest('hex');
}

module.exports = { hashToken };
